name: Tests

on:
  push:
    branches: [master]
  pull_request:
    # types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install yarn packages
        run: yarn install --frozen-lockfile
      - name: Typescript Compile
        run: yarn tsc
      - name: Tests (Jest)
        run: yarn test
